//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygulama01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public int BolumID { get; set; }
        public int BolumFakulteID { get; set; }
        public string BolumAdi { get; set; }
        public Nullable<int> BolumEkleyenID { get; set; }
        public Nullable<int> BolumDuzenleyenID { get; set; }
    
        public virtual Fakulte Fakulte { get; set; }
    }
}
